Squashed commit of the following: refs #5011
commit 13eaa8c3bfa0a5b53e9dab03b7b5450eed908123
Author: podhmo <podhmo+altair@beproud.jp>
Date:   Tue Aug 20 14:14:30 2013 +0900

    ValueError: insecure stringが出る場合もあった refs #5011